# Generated by Django 4.2.3 on 2023-07-15 15:41

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=20)),
                ('Sex', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('DOR', models.DateTimeField(auto_now_add=True)),
                ('LLD', models.DateTimeField(auto_now=True)),
                ('Avatar', models.ImageField(blank=True, default=users.models.default_avatar, null=True, upload_to='avatars/')),
                ('AD', models.TextField(default='')),
            ],
        ),
    ]
