# Generated by Django 4.2.3 on 2023-07-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('date', models.DateField(verbose_name='Date of Registration')),
                ('about', models.CharField(max_length=250, verbose_name='About')),
                ('photo', models.ImageField(upload_to='user_photos/', verbose_name='Photo')),
            ],
        ),
    ]
