# Generated by Django 4.2.3 on 2023-07-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default='2012-12-12', verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='login', max_length=20, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=20, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='none', max_length=10, verbose_name='Sex'),
        ),
    ]
