# Generated by Django 4.2.3 on 2023-07-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='AD',
            field=models.TextField(blank=True),
        ),
    ]
