# Generated by Django 4.2.3 on 2023-07-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_password_hash_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_hash',
        ),
    ]
