# Generated by Django 4.2.3 on 2023-07-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
