# Generated by Django 4.2.3 on 2023-07-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['time_create']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['time_create', 'title']},
        ),
        migrations.AlterField(
            model_name='thread',
            name='full_text',
            field=models.TextField(verbose_name='Full text'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of publication'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Time of update'),
        ),
    ]
