# Generated by Django 4.2.3 on 2023-07-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
    ]
