# Generated by Django 4.2.3 on 2023-07-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_remove_comment_user_remove_thread_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thread',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
