# Generated by Django 4.2.3 on 2023-07-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_alter_comment_options_comment_rating_thread_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='rating',
        ),
    ]
