# Generated by Django 4.2.3 on 2023-07-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_thread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='date',
        ),
        migrations.AddField(
            model_name='thread',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=1988, verbose_name='Time_of_publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Time_of_update'),
        ),
    ]
