# Generated by Django 4.2.3 on 2023-07-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_comment_rating_thread_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='rating',
        ),
    ]
