# Generated by Django 4.2.3 on 2023-08-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0010_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
