# Generated by Django 4.2.3 on 2023-08-01 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0011_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_object_id', models.PositiveIntegerField()),
                ('liked_object_type', models.CharField(choices=[('Thread', 'Thread'), ('Comment', 'Comment')], max_length=7)),
                ('like_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'liked_object_id', 'liked_object_type')},
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='threads.rating'),
        ),
        migrations.AddField(
            model_name='thread',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='threads.rating'),
        ),
    ]
